# Generated by Django 3.2.6 on 2021-08-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('C', 'Car'), ('M', 'Motorbike')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoa.personcustumer')),
                ('vehicle', models.ManyToManyField(to='garagem.Vehicle')),
            ],
        ),
    ]
